
version: '2.17.2'
services:
  
  db:
    image: alejandrodaw1/db:v3
    restart: always
    environment:
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "54320:5432"

  web:
      image: alejandrodaw1/web:v6
      ports:
      - '8000:8000'
      restart: always
      command: >
        sh -c " python /usr/src/app/prueba/manage.py makemigrations
        && python /usr/src/app/prueba/manage.py migrate
        && python /usr/src/app/prueba/manage.py runserver 0.0.0.0:8000"

      depends_on:
        - db



  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: example@example.com
      PGADMIN_DEFAULT_PASSWORD: admin

  